# Exynos DEVFREQ Drivers
obj-$(CONFIG_ARM_EXYNOS_DEVFREQ)	+= exynos-devfreq.o
obj-$(CONFIG_ARM_EXYNOS8895_BUS_DEVFREQ)+= exynos8895_bus_mif.o exynos8895_bus_int.o exynos8895_bus_disp.o exynos8895_bus_cam.o exynos8895_bus_intcam.o
obj-$(CONFIG_EXYNOS_ALT_DVFS)		+= exynos-ppc.o
